#!/usr/bin/env python3
"""git2ai.py — Export a git repository as structured XML context for AI assistants."""

from __future__ import annotations

import argparse
import fnmatch
import itertools
import os
import re
import shutil
import stat
import subprocess
import sys
import xml.sax.saxutils as saxutils
from collections import Counter, defaultdict
from contextlib import contextmanager
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Iterator, Optional

BINARY_EXTS: frozenset[str] = frozenset(
    {
        "png",
        "jpg",
        "jpeg",
        "gif",
        "ico",
        "svg",
        "webp",
        "bmp",
        "tiff",
        "heic",
        "heif",
        "ai",
        "psd",
        "indd",
        "sketch",
        "fig",
        "3ds",
        "fbx",
        "glb",
        "gltf",
        "blend",
        "mp3",
        "mp4",
        "mov",
        "avi",
        "mpg",
        "mpeg",
        "flv",
        "ogg",
        "wav",
        "flac",
        "zip",
        "tar",
        "gz",
        "7z",
        "rar",
        "iso",
        "img",
        "dmg",
        "exe",
        "dll",
        "so",
        "dylib",
        "bin",
        "class",
        "pyc",
        "pyo",
        "o",
        "obj",
        "a",
        "lib",
        "wasm",
        "keystore",
        "sqlite",
        "db",
        "woff",
        "woff2",
        "ttf",
        "eot",
        "xls",
        "xlsx",
        "xlsm",
        "doc",
        "docx",
        "ppt",
        "pptx",
        "odt",
        "ods",
        "odp",
        "npy",
        "npz",
        "parquet",
        "feather",
        "pkl",
        "pickle",
        "h5",
        "hdf5",
        "egg",
        "whl",
        "jar",
        "war",
        "ear",
        "apk",
        "aab",
        "app",
        "pem",
        "crt",
        "key",
        "p12",
        "jks",
        "pfx",
        "asc",
        "gpg",
    }
)

BINARY_MAGIC: tuple[bytes, ...] = (
    b"%PDF-",
    b"\x89PNG\r\n\x1a\n",
    b"\xff\xd8\xff",
    b"GIF87a",
    b"GIF89a",
    b"PK\x03\x04",
    b"\x7fELF",
    b"\xca\xfe\xba\xbe",
    b"\xce\xfa\xed\xfe",
    b"\xcf\xfa\xed\xfe",
    b"\xfe\xed\xfa\xce",
    b"\xfe\xed\xfa\xcf",
    b"BM",
    b"\x00\x00\x01\x00",
    b"RIFF",
    b"8BPS",
    b"II*\x00",
    b"MM\x00*",
    b"\x1f\x8b",
    b"7z\xbc\xaf\x27\x1c",
    b"Rar!\x1a\x07",
)

IGNORE_DIRS: frozenset[str] = frozenset(
    {
        ".git",
        ".svn",
        ".hg",
        ".bzr",
        "node_modules",
        "bower_components",
        "vendor",
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".venv",
        "venv",
        "env",
        ".tox",
        ".nox",
        ".eggs",
        "site-packages",
        "build",
        "dist",
        "out",
        "target",
        ".next",
        ".nuxt",
        ".svelte-kit",
        ".idea",
        ".vscode",
        ".vs",
        ".eclipse",
        ".settings",
        ".gradle",
        ".mvn",
        "coverage",
        ".cache",
        ".parcel-cache",
        ".turbo",
        ".vercel",
        ".netlify",
        "__generated__",
        "compiled",
    }
)

IDENTITY_NAMES: frozenset[str] = frozenset(
    {
        "package.json",
        "pyproject.toml",
        "setup.py",
        "requirements.txt",
        "cargo.toml",
        "go.mod",
        "pom.xml",
        "build.gradle",
        "dockerfile",
        "makefile",
        "docker-compose.yml",
        "tsconfig.json",
        "jest.config.js",
        "jest.config.ts",
        "vite.config.ts",
        "vite.config.js",
        "webpack.config.js",
        "webpack.config.ts",
        "babel.config.json",
        "babel.config.js",
        ".gitlab-ci.yml",
        "azure-pipelines.yml",
        "jenkinsfile",
    }
)

IDENTITY_PREFIXES: tuple[str, ...] = ("readme", "contributing", "changelog")

GENERATED_NAMES: frozenset[str] = frozenset(
    {
        "yarn.lock",
        "pnpm-lock.yaml",
        "package-lock.json",
        "poetry.lock",
        "go.sum",
        "cargo.lock",
        "gemfile.lock",
        "composer.lock",
        "mix.lock",
        "packages.lock.json",
    }
)

GENERATED_SUFFIXES: tuple[str, ...] = (
    ".min.js",
    ".min.css",
    ".tsbuildinfo",
    ".map",
    "-lock.json",
    ".lockb",
)

GENERATED_MARKERS: tuple[str, ...] = (
    "auto-generated",
    "do not edit",
    "generated by",
    "code generated",
    "this file was generated",
)

SENSITIVE_NAMES: frozenset[str] = frozenset({".env"})
SENSITIVE_PREFIXES: tuple[str, ...] = (".env.",)
SENSITIVE_ALLOWLIST: frozenset[str] = frozenset(
    {".env.example", ".env.sample", ".env.template"}
)

SECRET_PATTERNS: tuple[tuple[str, re.Pattern[str], str], ...] = (
    ("OPENAI_API_KEY", re.compile(r"\bsk-[A-Za-z0-9\-_]{20,}\b"), "[REDACTED:{label}]"),
    ("AWS_ACCESS_KEY_ID", re.compile(r"\bAKIA[0-9A-Z]{16}\b"), "[REDACTED:{label}]"),
    (
        "AWS_SECRET_ACCESS_KEY",
        re.compile(r"""(?i)aws(?:.{0,20}?)(?:secret)?['\"\s:=]+([A-Za-z0-9/+]{40})"""),
        "[REDACTED:{label}]",
    ),
    ("GITHUB_PAT", re.compile(r"\bghp_[A-Za-z0-9]{36,}\b"), "[REDACTED:{label}]"),
    ("GITHUB_OAUTH", re.compile(r"\bgho_[A-Za-z0-9]{36,}\b"), "[REDACTED:{label}]"),
    (
        "GITHUB_FINEGRAINED",
        re.compile(r"\bgithub_pat_[A-Za-z0-9_]{60,}\b"),
        "[REDACTED:{label}]",
    ),
    (
        "GITHUB_APP",
        re.compile(r"\b(?:ghu|ghs|ghr)_[A-Za-z0-9]{36,}\b"),
        "[REDACTED:{label}]",
    ),
    (
        "SLACK_TOKEN",
        re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}"),
        "[REDACTED:{label}]",
    ),
    ("GOOGLE_API_KEY", re.compile(r"\bAIza[0-9A-Za-z\-_]{35}\b"), "[REDACTED:{label}]"),
    (
        "STRIPE_KEY",
        re.compile(r"\b(?:sk|pk)_(?:live|test)_[A-Za-z0-9]{24,}\b"),
        "[REDACTED:{label}]",
    ),
    (
        "JWT",
        re.compile(
            r"\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b"
        ),
        "[REDACTED:{label}]",
    ),
    (
        "BEARER_TOKEN",
        re.compile(r"\bBearer\s+[A-Za-z0-9\-_\.=]{20,}"),
        "Bearer [REDACTED:{label}]",
    ),
)

PRIVATE_KEY_BEGIN_RE = re.compile(
    r"-----BEGIN (?:RSA |EC |OPENSSH |DSA |PGP )?PRIVATE KEY-----"
)
PRIVATE_KEY_END_RE = re.compile(
    r"-----END (?:RSA |EC |OPENSSH |DSA |PGP )?PRIVATE KEY-----"
)
PRIVATE_KEY_BODY_LABEL = "[REDACTED:PRIVATE_KEY_MATERIAL]"

_XML_INVALID_RE = re.compile("[\x00-\x08\x0b\x0c\x0e-\x1f\ud800-\udfff\ufffe\uffff]")
_SENSITIVE_REF_RE = re.compile(
    r"(?<![.\w-])\.env(?:\.[^\s,;:'\"()\[\]<>]*)?", re.IGNORECASE
)
_DIFF_HEADER_RE = re.compile(r"^diff --git a/(.+?) b/(.+)$")
_GLOB_CHARS_RE = re.compile(r"[*?\[]")
_SKELETON_RE = re.compile(
    r"^\s*(?:export\s+|public\s+|private\s+|protected\s+|static\s+|async\s+|abstract\s+|declare\s+|pub\s+)*"
    r"(?:class|def|function|func|interface|struct|type|enum|protocol|extension|trait|impl|namespace)\s+[A-Za-z_]"
    r"|^\s*export\s+(?:const|let|var|default)\s+"
    r"|^\s*(?:public|private|protected)\s+(?:static\s+)?(?:[A-Za-z_<>]+\s+)[A-Za-z_]+\s*\("
    r"|^\s*type\s+[A-Za-z_]+\s*="
    r"|^\s*const\s+[A-Za-z_]+\s*=\s*(?:async\s+)?(?:\([^)]*\)\s*=>|=>)"
    r"|^\s*func\s+(?:\([^)]*\)\s*)?[A-Za-z_]+\s*\("
    r"|^\s*@(?:property|staticmethod|classmethod|dataclass|override|Injectable)",
    re.MULTILINE,
)

_JS_IMPORT_RE = re.compile(r"""import\s+(?:[\s\S]*?\s+from\s+)?['"]([^'"]+)['"]""")
_JS_REQUIRE_RE = re.compile(r"""require\(\s*['"]([^'"]+)['"]\s*\)""")
_PY_IMPORT_RE = re.compile(r"^\s*import\s+([\w.]+)", re.MULTILINE)
_PY_FROM_RE = re.compile(r"^\s*from\s+([\w.]+)\s+import", re.MULTILINE)
_JVM_IMPORT_RE = re.compile(r"^\s*import\s+([\w.]+)", re.MULTILINE)
_RUBY_REQUIRE_RE = re.compile(
    r'^\s*require(?:_relative)?\s+["\']([^"\']+)["\']', re.MULTILINE
)
_RUST_USE_RE = re.compile(r"^\s*use\s+([\w:]+)", re.MULTILINE)
_RUST_MOD_RE = re.compile(r"^\s*mod\s+(\w+)", re.MULTILINE)
_GO_IMPORT_RE = re.compile(r'^\s*"(\w[\w./-]*)"', re.MULTILINE)

_IMPORT_PATTERNS: dict[str, tuple[re.Pattern[str], ...]] = {
    "js": (_JS_IMPORT_RE, _JS_REQUIRE_RE),
    "cjs": (_JS_REQUIRE_RE,),
    "mjs": (_JS_IMPORT_RE,),
    "jsx": (_JS_IMPORT_RE,),
    "ts": (_JS_IMPORT_RE,),
    "tsx": (_JS_IMPORT_RE,),
    "py": (_PY_IMPORT_RE, _PY_FROM_RE),
    "rb": (_RUBY_REQUIRE_RE,),
    "rs": (_RUST_USE_RE, _RUST_MOD_RE),
    "go": (_GO_IMPORT_RE,),
    "java": (_JVM_IMPORT_RE,),
    "kt": (_JVM_IMPORT_RE,),
}

MODULE_EXTS: tuple[str, ...] = (
    "",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".mjs",
    ".cjs",
    ".py",
    ".rb",
    ".rs",
    ".go",
    ".json",
)
INDEX_NAMES: tuple[str, ...] = (
    "index.js",
    "index.ts",
    "index.jsx",
    "index.tsx",
    "__init__.py",
    "mod.rs",
    "index.rb",
)

NOISE_WEIGHT_MINIFY = 0.4
NOISE_WEIGHT_DIVERSITY = 0.6

PRIORITY_IDENTITY = 0.30
PRIORITY_CHURN = 0.20
PRIORITY_COCHANGE = 0.10
PRIORITY_MODIFIED = 0.20
PRIORITY_TESTED = 0.10
PRIORITY_SIZE_PENALTY = 0.10

UNTRACKED_STATUS = "??"
EMPTY_TREE_SHA = "4b825dc642cb6eb9a060e54bf8d69288fbee4904"


class EmitDecision(Enum):
    FULL = "full"
    SKELETON = "skeleton"
    STUB = "stub"


@dataclass
class FileNode:
    path: str
    obj_sha: Optional[bytes] = None
    status: str = ""
    is_binary: bool = False
    is_symlink: bool = False
    is_identity: bool = False
    is_sensitive: bool = False
    in_worktree: bool = False
    wt_dirty: bool = False
    noise_score: float = 0.0
    noise_reason: str = ""
    priority_score: float = 0.0
    line_count: int = 0


@dataclass
class FileEdge:
    src: str
    dst: str
    kind: str
    weight: float = 1.0
    meta: str = ""


@dataclass
class FileGraph:
    edges: list[FileEdge] = field(default_factory=list)
    _out: dict[str, list[FileEdge]] = field(default_factory=dict)
    _in: dict[str, list[FileEdge]] = field(default_factory=dict)

    def add_edge(self, edge: FileEdge) -> None:
        self.edges.append(edge)
        self._out.setdefault(edge.src, []).append(edge)
        self._in.setdefault(edge.dst, []).append(edge)

    def partners(self, path: str) -> Iterator[tuple[FileEdge, bool]]:
        for edge in self._out.get(path, []):
            yield edge, True
        for edge in self._in.get(path, []):
            yield edge, False

    def degree(self, path: str, kind: str) -> int:
        return sum(1 for e, _ in self.partners(path) if e.kind == kind)


@dataclass
class SectionSpec:
    name: str
    priority: float
    emitter: Callable[[XmlEmitter, list[FileNode], RepoContext], None]


@dataclass
class RepoContext:
    repo_root: str
    env: dict[str, str]
    target_head: str
    range_args: list[str]
    custom_ignores: list[str]
    redact_secrets: bool
    max_file_lines: int
    skeleton_lines: int
    diff_per_file: int
    noise_threshold: float
    excluded_paths: set[str] = field(default_factory=set)
    churn_hotspots: set[str] = field(default_factory=set)
    cochange_pairs: Counter = field(default_factory=Counter)
    test_pairs: dict[str, str] = field(default_factory=dict)
    diffs: dict[str, str] = field(default_factory=dict)
    filtered_files: dict[str, str] = field(default_factory=dict)
    file_graph: FileGraph = field(default_factory=FileGraph)
    files_full: list[str] = field(default_factory=list)
    files_skeleton: list[str] = field(default_factory=list)
    files_stub: list[str] = field(default_factory=list)
    noise_stubs: dict[str, str] = field(default_factory=dict)
    capped_diff_files: list[str] = field(default_factory=list)
    section_errors: list[str] = field(default_factory=list)


def warn(message: str) -> None:
    sys.stderr.write(f"Warning: {message}\n")


def git_env() -> dict[str, str]:
    env = os.environ.copy()
    env["LC_ALL"] = "C"
    return env


@contextmanager
def git_batch_reader(env: dict[str, str]) -> Iterator["GitObjectReader"]:
    reader = GitObjectReader(env)
    try:
        yield reader
    finally:
        reader.close()


class GitObjectReader:
    def __init__(self, env: dict[str, str]):
        self._env = env
        self._proc: Optional[subprocess.Popen] = None

    def _ensure(self) -> subprocess.Popen:
        if self._proc is None:
            self._proc = subprocess.Popen(
                ["git", "cat-file", "--batch"],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                env=self._env,
            )
        assert self._proc.stdin is not None and self._proc.stdout is not None
        return self._proc

    def read(self, obj_sha: bytes) -> Optional[bytes]:
        proc = self._ensure()
        assert proc.stdin is not None and proc.stdout is not None
        try:
            proc.stdin.write(obj_sha + b"\n")
            proc.stdin.flush()
        except BrokenPipeError:
            return None

        header = proc.stdout.readline().split()
        if len(header) < 3 or not header[2].isdigit():
            return None

        size = int(header[2])
        raw = read_exact(proc.stdout, size)
        read_exact(proc.stdout, 1)
        return raw

    def close(self) -> None:
        if self._proc is None:
            return
        try:
            if self._proc.stdin:
                self._proc.stdin.close()
            self._proc.wait()
        except OSError:
            pass
        self._proc = None


def read_exact(pipe, size: int) -> bytes:
    buf = bytearray()
    while len(buf) < size:
        chunk = pipe.read(size - len(buf))
        if not chunk:
            break
        buf.extend(chunk)
    return bytes(buf)


def read_regular_file(path: str) -> Optional[bytes]:
    try:
        st = os.lstat(path)
    except OSError:
        return None
    if not stat.S_ISREG(st.st_mode):
        return None
    try:
        with open(path, "rb") as fh:
            return fh.read()
    except OSError:
        return None


def resolve_repo_root(repo_dir: str, env: dict[str, str]) -> str:
    result = subprocess.run(
        ["git", "-C", repo_dir, "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
        errors="replace",
        env=env,
    )
    if result.returncode != 0:
        sys.exit(f"Error: '{repo_dir}' is not a valid git worktree.")
    return result.stdout.strip()


def split_range_expr(expr: str) -> tuple[Optional[str], Optional[str]]:
    for sep in ("...", ".."):
        if sep in expr:
            left, right = expr.split(sep, 1)
            return left or None, right or None
    return None, None


def verify_ref(ref: str, label: str, env: dict[str, str]) -> None:
    chk = subprocess.run(
        ["git", "rev-parse", "--verify", "--quiet", ref],
        capture_output=True,
        text=True,
        env=env,
    )
    if chk.returncode != 0:
        sys.exit(f"Error: could not resolve {label} '{ref}'.")


def resolve_target_head(range_args: list[str], env: dict[str, str]) -> str:
    expr = range_args[-1]
    from_ref, to_ref = split_range_expr(expr)

    if from_ref is None and to_ref is None:
        verify_ref(expr, "git ref", env)
        result = subprocess.run(
            ["git", "rev-parse", expr], capture_output=True, text=True, env=env
        )
        if result.returncode != 0:
            sys.exit(f"Error: could not resolve git ref '{expr}'.")
        return result.stdout.strip()

    if from_ref:
        verify_ref(from_ref, "--from-commit ref", env)
    if to_ref:
        verify_ref(to_ref, "git ref", env)

    target = to_ref or "HEAD"
    result = subprocess.run(
        ["git", "rev-parse", target], capture_output=True, text=True, env=env
    )
    if result.returncode != 0:
        sys.exit(f"Error: could not resolve git ref '{target}'.")
    return result.stdout.strip()


def build_range_args(from_commit: str, to_commit: str) -> list[str]:
    if from_commit and ".." in from_commit:
        return [from_commit]
    if from_commit and to_commit:
        return [f"{from_commit}..{to_commit}"]
    if from_commit:
        return [f"{from_commit}..HEAD"]
    if to_commit:
        return [to_commit]
    return ["HEAD"]


def iter_porcelain_status(env: dict[str, str]) -> Iterator[tuple[str, str]]:
    proc = subprocess.run(
        [
            "git",
            "-c",
            "core.quotepath=false",
            "status",
            "--porcelain=v1",
            "-z",
            "-uall",
        ],
        capture_output=True,
        text=True,
        errors="replace",
        env=env,
    )
    if proc.returncode != 0:
        warn("git status failed.")
        return

    parts = proc.stdout.split("\x00")
    i = 0
    while i < len(parts):
        entry = parts[i]
        if not entry or len(entry) < 4:
            i += 1
            continue

        xy = entry[:2]
        path = entry[3:]

        if xy[0] in ("R", "C") and i + 1 < len(parts):
            src = parts[i + 1]
            yield xy, path
            yield "D ", src
            i += 2
            continue

        yield xy, path
        i += 1


def iter_ls_tree(target_head: str, env: dict[str, str]) -> Iterator[tuple[str, bytes]]:
    proc = subprocess.run(
        ["git", "ls-tree", "-r", "-z", target_head],
        capture_output=True,
        env=env,
    )
    if proc.returncode != 0:
        warn(f"git ls-tree failed for '{target_head}'.")
        return

    for record in proc.stdout.split(b"\x00"):
        if not record:
            continue
        try:
            meta, raw_path = record.split(b"\t", 1)
        except ValueError:
            continue

        parts = meta.split(b" ")
        if len(parts) < 3 or parts[1] != b"blob":
            continue

        yield raw_path.decode("utf-8", errors="replace"), parts[2]


def strip_diff_path(token: str) -> str:
    path = token.split("\t")[0]
    if path.startswith(("a/", "b/")):
        return path[2:]
    return path


def parse_git_diff(text: str) -> dict[str, str]:
    diffs: dict[str, str] = {}
    current: list[str] = []
    key: Optional[str] = None
    old_path: Optional[str] = None

    def flush() -> None:
        if key is not None:
            diffs.setdefault(key, "\n".join(current))

    for line in text.splitlines():
        if line.startswith("diff --git "):
            flush()
            key = None
            old_path = None
            current = [line]
        elif line.startswith("--- "):
            old_path = strip_diff_path(line[4:])
            current.append(line)
        elif line.startswith("+++ "):
            new_path = strip_diff_path(line[4:])
            key = new_path if new_path != "/dev/null" else old_path
            current.append(line)
        elif current:
            current.append(line)

    flush()
    return diffs


def git_diff_all(env: dict[str, str]) -> dict[str, str]:
    result = subprocess.run(
        ["git", "-c", "core.quotepath=false", "diff", "HEAD", "--no-renames"],
        capture_output=True,
        text=True,
        errors="replace",
        env=env,
    )
    if result.returncode != 0:
        result = subprocess.run(
            [
                "git",
                "-c",
                "core.quotepath=false",
                "diff",
                EMPTY_TREE_SHA,
                "--no-renames",
            ],
            capture_output=True,
            text=True,
            errors="replace",
            env=env,
        )
    if result.returncode != 0:
        return {}
    return parse_git_diff(result.stdout)


def sanitize_sensitive(line: str) -> str:
    def repl(m: re.Match) -> str:
        matched = m.group(0)
        basename = os.path.basename(matched).lower()
        if basename in SENSITIVE_ALLOWLIST:
            return matched
        if basename in SENSITIVE_NAMES or any(
            basename.startswith(p) for p in SENSITIVE_PREFIXES
        ):
            return "[SENSITIVE_FILE]"
        return matched

    return _SENSITIVE_REF_RE.sub(repl, line)


class LineSanitizer:
    def __init__(self, redact: bool):
        self.redact = redact
        self._inside_key_block = False

    def reset(self) -> None:
        self._inside_key_block = False

    def __call__(self, line: str) -> str:
        line = sanitize_sensitive(line)
        if not self.redact:
            return line
        if PRIVATE_KEY_BEGIN_RE.search(line):
            self._inside_key_block = True
            return PRIVATE_KEY_BEGIN_RE.sub("[REDACTED:PRIVATE_KEY_BLOCK]", line)
        if self._inside_key_block:
            if PRIVATE_KEY_END_RE.search(line):
                self._inside_key_block = False
                return PRIVATE_KEY_END_RE.sub("[REDACTED:PRIVATE_KEY_BLOCK]", line)
            return PRIVATE_KEY_BODY_LABEL
        for label, pattern, template in SECRET_PATTERNS:
            line = pattern.sub(template.format(label=label), line)
        return line


def xml_escape_attr(value: Any) -> str:
    return saxutils.quoteattr(_XML_INVALID_RE.sub("", str(value)))


def xml_attrs(attrs: dict[str, Any]) -> str:
    return " ".join(f"{k}={xml_escape_attr(v)}" for k, v in attrs.items())


def xml_escape_text(text: str) -> str:
    cleaned = _XML_INVALID_RE.sub("", text)
    return cleaned.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def cdata_escape(text: str) -> str:
    return _XML_INVALID_RE.sub("", text).replace("]]>", "]]]]><![CDATA[>")


class XmlEmitter:
    def __init__(self, file_handle, ctx: RepoContext):
        self.f = file_handle
        self.ctx = ctx
        self.sanitizer = LineSanitizer(ctx.redact_secrets)

    def write(self, text: str) -> None:
        self.f.write(text)

    def begin_file(self) -> None:
        self.sanitizer.reset()

    def open_tag(
        self, tag: str, attrs: Optional[dict[str, Any]] = None, indent: str = ""
    ) -> None:
        head = f"<{tag}" + (f" {xml_attrs(attrs)}" if attrs else "") + ">\n"
        self.write(f"{indent}{head}")

    def close_tag(self, tag: str, indent: str = "") -> None:
        self.write(f"{indent}</{tag}>\n")

    def note(self, text: str, indent: str = "  ") -> None:
        self.write(f"{indent}<note>{xml_escape_text(text)}</note>\n")

    def comment(self, text: str, indent: str = "") -> None:
        safe = text.replace("--", "\u2013")
        self.write(f"{indent}<!-- {xml_escape_text(safe)} -->\n")

    def empty_element(self, indent: str, tag: str, attrs: dict[str, Any]) -> None:
        self.write(f"{indent}<{tag} {xml_attrs(attrs)} />\n")

    @contextmanager
    def cdata(self, indent: str = "  ") -> Iterator[None]:
        self.write(f"{indent}<![CDATA[\n")
        yield
        self.write(f"{indent}]]>\n")

    def line(self, text: str, indent: str = "") -> None:
        self.write(indent + cdata_escape(self.sanitizer(text)) + "\n")


def is_identity_file(path: str) -> bool:
    name = os.path.basename(path).lower()
    if name in IDENTITY_NAMES:
        return True
    if any(name == p or name.startswith(p + ".") for p in IDENTITY_PREFIXES):
        return True
    return path.startswith(".github/workflows/")


def is_generated_by_name(path: str) -> bool:
    name = os.path.basename(path).lower()
    if name in GENERATED_NAMES:
        return True
    return any(name.endswith(suf) for suf in GENERATED_SUFFIXES)


def is_sensitive_file(path: str) -> bool:
    name = os.path.basename(path).lower()
    if name in SENSITIVE_ALLOWLIST:
        return False
    return name in SENSITIVE_NAMES or any(
        name.startswith(p) for p in SENSITIVE_PREFIXES
    )


def ignore_reason(path: str, custom_ignores: list[str]) -> Optional[str]:
    for part in path.split("/"):
        if part in IGNORE_DIRS:
            return f"ignored_dir({part})"

    if is_generated_by_name(path):
        return "generated"

    if is_sensitive_file(path):
        return "sensitive"

    basename = os.path.basename(path)
    for pat in custom_ignores:
        if fnmatch.fnmatch(path, pat) or fnmatch.fnmatch(basename, pat):
            return f"custom_ignore({pat})"
        stripped = pat.strip("/")
        if stripped and not _GLOB_CHARS_RE.search(stripped):
            if path == stripped or path.startswith(stripped + "/"):
                return f"custom_ignore({pat})"

    basename_lower = basename.lower()
    ext = basename_lower.rsplit(".", 1)[-1] if "." in basename_lower else ""
    if ext in BINARY_EXTS:
        return "binary_ext"

    return None


def looks_binary_by_content(data: bytes) -> bool:
    if not data:
        return False
    if b"\x00" in data[:8192]:
        return True
    head = data[:8]
    return any(head.startswith(magic) for magic in BINARY_MAGIC)


def normalize_line_shape(line: str) -> str:
    s = line[1:] if line[:1] in "+-" else line
    s = re.sub(r"#[0-9a-fA-F]{3,8}\b", "#X", s)
    s = re.sub(r"-?\d+\.?\d*", "N", s)
    s = re.sub(r'"[^"]*"', '"S"', s)
    s = re.sub(r"'[^']*'", "'S'", s)
    s = re.sub(r"\b([a-zA-Z_][\w-]*?)-N\b", r"\1-N", s)
    s = re.sub(r"N+", "N", s)
    return s[:80]


def compute_diversity_ratio(lines: list[str], sample_size: int = 200) -> float:
    keys = [normalize_line_shape(l) for l in lines[:sample_size] if l.strip()]
    if not keys:
        return 1.0
    return len(set(keys)) / len(keys)


def compute_unique_shapes(lines: list[str], sample_size: int = 200) -> int:
    return len({normalize_line_shape(l) for l in lines[:sample_size] if l.strip()})


def compute_noise_score(
    node: FileNode, lines: list[str], raw: bytes
) -> tuple[float, str]:
    header = raw[:1024].decode("utf-8", errors="ignore").lower()
    for marker in GENERATED_MARKERS:
        if marker in header:
            return 1.0, f"content_marker('{marker}')"

    if b"sourceMappingURL" in raw[:8192]:
        return 1.0, "source_map_reference"

    if not lines:
        return 0.0, ""

    avg_len = sum(len(l) for l in lines) / len(lines)
    max_len = max(len(l) for l in lines)
    minify_score = min(1.0, max(avg_len / 500, max_len / 5000))

    if len(lines) > 50:
        ratio = compute_diversity_ratio(lines)
        shapes = compute_unique_shapes(lines)
        diversity_signal = (1.0 - ratio) * (1.0 - min(1.0, shapes / 15))
        reason = (
            f"minify_signal={minify_score:.2f},"
            f"diversity_signal={diversity_signal:.2f}"
            f"(ratio={ratio:.2f},shapes={shapes})"
        )
    else:
        diversity_signal = 0.0
        reason = f"minify_signal={minify_score:.2f}"

    score = (
        minify_score * NOISE_WEIGHT_MINIFY + diversity_signal * NOISE_WEIGHT_DIVERSITY
    )
    return score, reason


def detect_imports(path: str, content: bytes) -> list[str]:
    ext = path.rsplit(".", 1)[-1].lower() if "." in path else ""
    patterns = _IMPORT_PATTERNS.get(ext)
    if not patterns:
        return []

    text = content.decode("utf-8", errors="replace")
    refs: list[str] = []
    for pat in patterns:
        refs.extend(pat.findall(text))
    return refs


BARE_MODULE_EXTS: tuple[str, ...] = (
    ".py",
    "/__init__.py",
    ".js",
    "/index.js",
    ".ts",
    "/index.ts",
    ".jsx",
    "/index.jsx",
    ".tsx",
    "/index.tsx",
    ".mjs",
    ".cjs",
    ".rb",
)


def resolve_import_to_path(
    ref: str, src_path: str, all_paths: set[str]
) -> Optional[str]:
    if not ref:
        return None

    if not ref.startswith(".") and "/" not in ref:
        candidates = [ref]
        if "." in ref and not ref.endswith((".js", ".ts", ".py", ".go")):
            candidates.append(ref.replace(".", "/"))
        for base in candidates:
            for ext in BARE_MODULE_EXTS:
                resolved = base + ext
                if resolved in all_paths:
                    return resolved
        return None

    src_dir = os.path.dirname(src_path)
    candidate = os.path.normpath(os.path.join(src_dir, ref))

    if candidate in all_paths:
        return candidate

    for ext in MODULE_EXTS:
        if candidate + ext in all_paths:
            return candidate + ext

    for idx in INDEX_NAMES:
        resolved = os.path.join(candidate, idx)
        if resolved in all_paths:
            return resolved

    return None


def detect_test_pairs(all_paths: set[str]) -> dict[str, str]:
    test_index: dict[str, list[str]] = defaultdict(list)

    for tp in all_paths:
        tb = os.path.basename(tp)
        tn, _, te = tb.rpartition(".")
        is_test_by_name = te and ("test" in tn.lower() or "spec" in tn.lower())
        is_test_by_dir = any(
            seg in {"tests", "__tests__", "test"} for seg in tp.split("/")
        )
        if is_test_by_name or is_test_by_dir:
            test_index[tb].append(tp)

    pairs: dict[str, str] = {}

    for p in all_paths:
        dir_part = os.path.dirname(p)
        base = os.path.basename(p)
        name, _, ext = base.rpartition(".")

        if not ext or "test" in name.lower() or "spec" in name.lower():
            continue

        candidates: list[str] = [
            os.path.join(dir_part, f"{name}.test.{ext}"),
            os.path.join(dir_part, f"{name}.spec.{ext}"),
            os.path.join(dir_part, f"test_{base}"),
            os.path.join(dir_part, f"{name}_test.{ext}"),
            os.path.join(dir_part, "tests", f"test_{base}"),
            os.path.join(dir_part, "tests", f"{name}.test.{ext}"),
            os.path.join(dir_part, "tests", f"{name}.spec.{ext}"),
            os.path.join(dir_part, "tests", f"{base}"),
            os.path.join(dir_part, "__tests__", f"{name}.test.{ext}"),
            os.path.join(dir_part, "__tests__", f"{name}.spec.{ext}"),
            os.path.join(dir_part, "__tests__", f"{base}"),
        ]

        parent = dir_part
        for _ in range(8):
            new_parent = os.path.dirname(parent)
            if not new_parent or new_parent == parent:
                break
            parent = new_parent
            candidates.extend(
                [
                    os.path.join(parent, "tests", f"test_{base}"),
                    os.path.join(parent, "tests", f"test_{name}.{ext}"),
                    os.path.join(parent, "tests", f"{name}_test.{ext}"),
                    os.path.join(parent, "tests", f"{name}.test.{ext}"),
                    os.path.join(parent, "tests", f"{name}.spec.{ext}"),
                    os.path.join(parent, "tests", f"{base}"),
                    os.path.join(parent, "test", f"test_{base}"),
                    os.path.join(parent, "test", f"{name}.test.{ext}"),
                    os.path.join(parent, "test", f"{base}"),
                    os.path.join(parent, "__tests__", f"{name}.test.{ext}"),
                    os.path.join(parent, "__tests__", f"{name}.spec.{ext}"),
                    os.path.join(parent, "__tests__", f"{base}"),
                ]
            )

        for c in candidates:
            if c in all_paths and c != p:
                pairs[p] = c
                break

        if p not in pairs:
            for test_key in (
                f"test_{base}",
                f"test_{name}.{ext}",
                f"{name}_test.{ext}",
                f"{name}.test.{ext}",
                f"{name}.spec.{ext}",
                base,
            ):
                for tp in test_index.get(test_key, []):
                    if tp != p:
                        pairs[p] = tp
                        break
                if p in pairs:
                    break

    return pairs


def compute_churn_metrics(
    range_args: list[str], custom_ignores: list[str], env: dict[str, str]
) -> tuple[Counter, Counter]:
    log_cmd = [
        "git",
        "log",
        "-n",
        "2000",
        "--format=COMMIT|%an",
        "--name-only",
    ] + range_args

    proc = subprocess.run(
        log_cmd, capture_output=True, text=True, errors="replace", env=env
    )
    if proc.returncode != 0:
        warn("git log failed while computing metrics.")
        return Counter(), Counter()

    file_churn: Counter = Counter()
    commit_files: dict[int, set] = {}

    current_commit = 0

    for raw_line in proc.stdout.splitlines():
        line = raw_line.rstrip("\r")

        if line.startswith("COMMIT|"):
            current_commit += 1
            commit_files[current_commit] = set()
        elif (
            current_commit > 0
            and line
            and not is_ignored(line, custom_ignores)
            and not is_generated_by_name(line)
        ):
            commit_files[current_commit].add(line)
            file_churn[line] += 1

    co_change: Counter = Counter()
    for fset in commit_files.values():
        if len(fset) > 30:
            continue
        for pair in itertools.combinations(sorted(fset), 2):
            co_change[pair] += 1

    return file_churn, co_change


def is_ignored(path: str, custom_ignores: list[str]) -> bool:
    return ignore_reason(path, custom_ignores) is not None


def register_worktree_facts(node: FileNode) -> None:
    try:
        st = os.lstat(node.path)
        node.is_symlink = stat.S_ISLNK(st.st_mode)
        node.in_worktree = stat.S_ISREG(st.st_mode) or node.is_symlink
    except OSError:
        node.is_symlink = False
        node.in_worktree = False


def enumerate_nodes(ctx: RepoContext) -> list[FileNode]:
    nodes: dict[str, FileNode] = {}

    def make_node(path: str, obj_sha: Optional[bytes], status: str) -> FileNode:
        node = FileNode(path=path, obj_sha=obj_sha, status=status)
        node.is_identity = is_identity_file(path)
        node.is_sensitive = is_sensitive_file(path)
        node.wt_dirty = (
            status != UNTRACKED_STATUS
            and len(status) >= 2
            and status[1] not in (" ", "D")
        )
        register_worktree_facts(node)
        return node

    for path, obj_sha in iter_ls_tree(ctx.target_head, ctx.env):
        if path in ctx.excluded_paths:
            continue
        reason = ignore_reason(path, ctx.custom_ignores)
        if reason:
            ctx.filtered_files[path] = reason
            continue
        nodes[path] = make_node(path, obj_sha, " ")

    for xy, path in iter_porcelain_status(ctx.env):
        if path in ctx.excluded_paths:
            continue
        reason = ignore_reason(path, ctx.custom_ignores)
        if reason:
            ctx.filtered_files[path] = reason
            continue
        if path in nodes:
            existing = nodes[path]
            existing.status = xy
            existing.wt_dirty = (
                xy != UNTRACKED_STATUS and len(xy) >= 2 and xy[1] not in (" ", "D")
            )
        else:
            nodes[path] = make_node(path, None, xy)

    return list(nodes.values())


def scan_node_content(
    node: FileNode, reader: GitObjectReader, ctx: RepoContext
) -> Optional[bytes]:
    if not node.in_worktree or node.is_symlink:
        return None
    data = read_regular_file(node.path)
    if data is not None:
        return data
    if node.obj_sha:
        return reader.read(node.obj_sha)
    return None


def analyze_nodes(nodes: list[FileNode], ctx: RepoContext) -> None:
    all_paths = {n.path for n in nodes}
    graph = ctx.file_graph

    with git_batch_reader(ctx.env) as reader:
        for node in nodes:
            data = scan_node_content(node, reader, ctx)
            if data is None:
                continue

            node.is_binary = looks_binary_by_content(data)
            if node.is_binary:
                continue

            lines = data.decode("utf-8", errors="replace").splitlines()
            node.line_count = len(lines)
            node.noise_score, node.noise_reason = compute_noise_score(node, lines, data)

            for ref in detect_imports(node.path, data):
                resolved = resolve_import_to_path(ref, node.path, all_paths)
                if resolved and resolved != node.path:
                    graph.add_edge(FileEdge(node.path, resolved, "import", 1.0, ref))


def finalize_graph(nodes: list[FileNode], ctx: RepoContext) -> None:
    all_paths = {n.path for n in nodes}
    graph = ctx.file_graph

    for src, test in ctx.test_pairs.items():
        if src in all_paths and test in all_paths:
            graph.add_edge(FileEdge(src, test, "test", 1.0, ""))

    for (f1, f2), count in ctx.cochange_pairs.most_common(50):
        if count > 1 and f1 in all_paths and f2 in all_paths:
            graph.add_edge(
                FileEdge(f1, f2, "cochange", float(count), f"co-commits={count}")
            )


def compute_priority_score(node: FileNode, ctx: RepoContext) -> float:
    score = 0.0

    if node.is_identity:
        score += PRIORITY_IDENTITY

    if node.path in ctx.churn_hotspots:
        score += PRIORITY_CHURN

    centrality = ctx.file_graph.degree(node.path, "cochange")
    score += min(PRIORITY_COCHANGE, centrality * 0.01)

    if node.status and node.status != UNTRACKED_STATUS:
        score += PRIORITY_MODIFIED

    if node.path in ctx.test_pairs or ctx.file_graph.degree(node.path, "test") > 0:
        score += PRIORITY_TESTED

    if node.line_count > ctx.max_file_lines:
        score -= PRIORITY_SIZE_PENALTY

    return max(0.0, min(1.0, score))


def decide_emission(node: FileNode, ctx: RepoContext) -> EmitDecision:
    if node.noise_score >= ctx.noise_threshold:
        return EmitDecision.STUB
    if node.is_symlink or node.is_binary or not node.in_worktree:
        return EmitDecision.STUB
    if node.line_count > ctx.max_file_lines:
        return EmitDecision.SKELETON
    return EmitDecision.FULL


SECTION_REGISTRY: list[SectionSpec] = []


def register_section(name: str, priority: float) -> Callable:
    def decorator(func: Callable) -> Callable:
        SECTION_REGISTRY.append(SectionSpec(name=name, priority=priority, emitter=func))
        return func

    return decorator


def stub_reason(node: FileNode, ctx: RepoContext) -> tuple[bool, str]:
    if node.noise_score >= ctx.noise_threshold:
        return True, f"noise({node.noise_reason})"
    if node.is_symlink:
        return True, "symlink"
    if node.is_binary:
        return True, "binary_or_empty"
    if not node.in_worktree:
        return True, "missing_from_worktree"
    return False, ""


def emit_file_content(
    emitter: XmlEmitter,
    node: FileNode,
    decision: EmitDecision,
    indent: str = "  ",
) -> None:
    ctx = emitter.ctx

    if decision == EmitDecision.STUB:
        ctx.files_stub.append(node.path)
        is_noise, reason = stub_reason(node, ctx)
        if is_noise:
            ctx.noise_stubs[node.path] = reason
        emitter.empty_element(
            indent, "file", {"path": node.path, "omitted": "true", "reason": reason}
        )
        return

    data = read_regular_file(node.path) if node.in_worktree else None
    if not data:
        ctx.files_stub.append(node.path)
        emitter.empty_element(
            indent, "file", {"path": node.path, "omitted": "true", "reason": "empty"}
        )
        return

    lines = data.decode("utf-8", errors="replace").splitlines()
    emitter.begin_file()

    if decision == EmitDecision.SKELETON:
        ctx.files_skeleton.append(node.path)
        emitter.open_tag("file", {"path": node.path, "mode": "skeleton"}, indent)
        with emitter.cdata(f"{indent}  "):
            emitter.line(
                f"/* ... [LARGE FILE: {len(lines)} LINES. EXTRACTING SEMANTIC SKELETON] ... */"
            )

            extracted = 0
            capturing_multiline = False

            for line in lines[: ctx.max_file_lines * 5]:
                if not capturing_multiline:
                    if _SKELETON_RE.search(line):
                        emitter.line(line)
                        extracted += 1
                        if not (
                            "{" in line or ";" in line or line.strip().endswith(")")
                        ):
                            capturing_multiline = True
                else:
                    emitter.line(line)
                    if "{" in line or ";" in line or line.strip().endswith(")"):
                        capturing_multiline = False

                if extracted >= ctx.skeleton_lines:
                    break

            if extracted == 0:
                for line in lines[:100]:
                    emitter.line(line)
                emitter.line("\n/* ... [NO INTERFACE DETECTED. TRUNCATED.] ... */")

        emitter.close_tag("file", indent)
        return

    ctx.files_full.append(node.path)
    emitter.open_tag("file", {"path": node.path, "mode": "full"}, indent)
    with emitter.cdata(f"{indent}  "):
        for line in lines:
            emitter.line(line)
    emitter.close_tag("file", indent)


@register_section("identity", 1.0)
def emit_identity(emitter: XmlEmitter, nodes: list[FileNode], ctx: RepoContext) -> None:
    identity_nodes = [n for n in nodes if n.is_identity]
    if not identity_nodes:
        return

    emitter.open_tag("project_identity")
    emitter.note(
        "Core orientation files, manifests, and documentation. Always prioritized."
    )

    for node in sorted(identity_nodes, key=lambda n: -n.priority_score):
        emit_file_content(emitter, node, decide_emission(node, ctx), indent="  ")

    emitter.close_tag("project_identity")


@register_section("directory_structure", 0.9)
def emit_directory_structure(
    emitter: XmlEmitter, nodes: list[FileNode], ctx: RepoContext
) -> None:
    emitter.open_tag("directory_structure")
    emitter.note("Filesystem tree of HEAD + working tree.")

    fs: dict = {}
    for node in nodes:
        cursor = fs
        for part in node.path.split("/"):
            cursor = cursor.setdefault(part, {})

    def render(node: dict, prefix: str = "") -> None:
        keys = sorted(node.keys())
        for i, key in enumerate(keys):
            is_last = i == len(keys) - 1
            connector = "└── " if is_last else "├── "
            suffix = "/" if node[key] else ""
            emitter.line(f"{prefix}{connector}{key}{suffix}")
            if node[key]:
                render(node[key], prefix + ("    " if is_last else "│   "))

    with emitter.cdata():
        render(fs)

    emitter.close_tag("directory_structure")


@register_section("file_graph", 0.85)
def emit_file_graph(
    emitter: XmlEmitter, nodes: list[FileNode], ctx: RepoContext
) -> None:
    if not ctx.file_graph.edges:
        return

    emitter.open_tag("file_graph")
    emitter.note(
        "Edges between files: imports, test pairs, co-change pairs. Use for navigation."
    )

    by_kind: dict[str, list[FileEdge]] = defaultdict(list)
    for edge in ctx.file_graph.edges:
        by_kind[edge.kind].append(edge)

    for kind in ("import", "test", "cochange"):
        edges = by_kind.get(kind, [])
        if not edges:
            continue

        emitter.open_tag("edges", {"kind": kind, "count": len(edges)}, "  ")
        for edge in edges[:200]:
            emitter.empty_element(
                "    ",
                "edge",
                {
                    "src": edge.src,
                    "dst": edge.dst,
                    "weight": edge.weight,
                    "meta": edge.meta,
                },
            )

        if len(edges) > 200:
            emitter.comment(f"{len(edges) - 200} more {kind} edges omitted", "    ")

        emitter.close_tag("edges", "  ")

    emitter.close_tag("file_graph")


@register_section("uncommitted_changes", 0.85)
def emit_uncommitted_changes(
    emitter: XmlEmitter, nodes: list[FileNode], ctx: RepoContext
) -> None:
    changed = [
        n
        for n in nodes
        if n.status and n.status.strip() and n.status != UNTRACKED_STATUS
    ]
    ad_nodes = [n for n in changed if n.status == "AD"]

    if not changed:
        return

    emitter.open_tag("uncommitted_changes")
    emitter.note(
        "Working tree changes not yet committed. Per-file diffs with dynamic noise stubbing."
    )

    total_emitted = 0
    skipped_noisy: list[str] = []

    sorted_changed = sorted(changed, key=lambda n: (-n.priority_score, n.noise_score))
    diff_cap = ctx.diff_per_file

    with emitter.cdata():
        emitter.line(
            f"/* Per-file diff cap: {diff_cap} lines.\n"
            f"   Dynamic noise threshold: {ctx.noise_threshold}.\n"
            f"   Noisy files are stubbed so they cannot crowd out source diffs. */"
        )

        for node in sorted_changed:
            diff_lines = ctx.diffs.get(node.path, "").splitlines()

            if node.noise_score >= ctx.noise_threshold:
                skipped_noisy.append(f"{node.path} ({node.noise_reason})")
                ctx.noise_stubs[node.path] = node.noise_reason
                emitter.line(
                    f"/* {node.path}  (status={node.status.strip() or 'M'} — "
                    f"DYNAMIC NOISE DETECTED: {node.noise_reason}.\n"
                    f"   Diff suppressed: {len(diff_lines)} lines. */"
                )
                continue

            if len(diff_lines) > diff_cap:
                ctx.capped_diff_files.append(f"{node.path} ({len(diff_lines)} lines)")
                emitter.line(
                    f"/* {node.path}  (status={node.status.strip() or 'M'} — "
                    f"large diff: {len(diff_lines)} lines exceeds per-file cap of "
                    f"{diff_cap}. Showing first {diff_cap} lines.) */"
                )
                for line in diff_lines[:diff_cap]:
                    emitter.line(line)
                emitter.line(f"/* ... [DIFF FOR {node.path} TRUNCATED] ... */")
                total_emitted += diff_cap
                continue

            for line in diff_lines:
                emitter.line(line)
            total_emitted += len(diff_lines)
            emitter.line("")

        for node in ad_nodes:
            emitter.line(
                f"/* {node.path}  (status=AD — STAGED-ADD-THEN-DELETED-FROM-DISK.\n"
                f"   File was staged via `git add` but is now missing from working tree.\n"
                f"   Run `git checkout -- {node.path}` to restore, or "
                f"`git rm --cached {node.path}` to unstage. */"
            )

        emitter.line("\n/* ── uncommitted_changes summary ── */")
        emitter.line(f"/* Total changed files: {len(changed)} */")
        emitter.line(f"/* Total diff lines emitted: {total_emitted} */")

        if skipped_noisy:
            emitter.line(
                f"/* Dynamically-detected noisy files stubbed ({len(skipped_noisy)}): */"
            )
            for p in skipped_noisy:
                emitter.line(f"/*   - {p} */")

        if ctx.capped_diff_files:
            emitter.line(
                f"/* Large diffs per-file-capped ({len(ctx.capped_diff_files)}): */"
            )
            for p in ctx.capped_diff_files:
                emitter.line(f"/*   - {p} */")

    emitter.close_tag("uncommitted_changes")


@register_section("working_tree_overrides", 0.8)
def emit_working_tree_overrides(
    emitter: XmlEmitter, nodes: list[FileNode], ctx: RepoContext
) -> None:
    modified = [
        n
        for n in nodes
        if n.wt_dirty
        and n.in_worktree
        and n.status != UNTRACKED_STATUS
        and not n.is_identity
        and n.noise_score < ctx.noise_threshold
    ]

    if not modified:
        return

    emitter.open_tag("working_tree_overrides")
    emitter.note(
        "Current on-disk content of tracked files whose working-tree version differs from HEAD."
    )

    for node in sorted(modified, key=lambda n: -n.priority_score):
        emit_file_content(emitter, node, decide_emission(node, ctx), indent="  ")

    emitter.close_tag("working_tree_overrides")


@register_section("untracked_files", 0.75)
def emit_untracked_files(
    emitter: XmlEmitter, nodes: list[FileNode], ctx: RepoContext
) -> None:
    untracked = [n for n in nodes if n.status == UNTRACKED_STATUS and not n.is_identity]
    if not untracked:
        return

    emitter.open_tag("untracked_files")
    emitter.note("New files in working tree not yet committed to git.")

    for node in sorted(untracked, key=lambda n: -n.priority_score):
        emit_file_content(emitter, node, decide_emission(node, ctx), indent="  ")

    emitter.close_tag("untracked_files")


@register_section("current_state", 0.6)
def emit_current_state(
    emitter: XmlEmitter, nodes: list[FileNode], ctx: RepoContext
) -> None:
    candidates = [
        n
        for n in nodes
        if not n.is_identity
        and n.status != UNTRACKED_STATUS
        and n.in_worktree
        and not n.wt_dirty
        and (n.obj_sha is not None or n.status[:1] in ("A", "R", "C"))
    ]

    if not candidates:
        return

    emitter.open_tag("current_state")
    emitter.note(
        "Files under line threshold are full. Truly massive files are reduced to skeletons."
    )

    for node in sorted(candidates, key=lambda n: -n.priority_score):
        emit_file_content(emitter, node, decide_emission(node, ctx), indent="  ")

    emitter.close_tag("current_state")


@register_section("recent_activity", 0.5)
def emit_recent_activity(
    emitter: XmlEmitter, nodes: list[FileNode], ctx: RepoContext
) -> None:
    emitter.open_tag("recent_activity")
    emitter.note(
        "The last 20 commits for immediate active context. Diff budget: 1000 lines per commit."
    )

    cmd = [
        "git",
        "log",
        "-n",
        "20",
        "-p",
        "--date=short",
        "--pretty=format:commit %H%nAuthor: %an%nDate: %ad%n%n%s%n",
    ] + ctx.range_args

    proc = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        errors="replace",
        env=ctx.env,
    )
    assert proc.stdout is not None

    diff_budget = 1000
    emitted_in_commit = 0
    in_diff = False
    suppress_file = False
    truncation_noted = False

    try:
        with emitter.cdata():
            for raw_line in proc.stdout:
                line = raw_line.rstrip("\r\n")

                if line.startswith("commit "):
                    in_diff = False
                    suppress_file = False
                    truncation_noted = False
                    emitted_in_commit = 0
                    emitter.line(line)
                    continue

                if line.startswith("diff --git "):
                    m = _DIFF_HEADER_RE.match(line)
                    suppress_file = bool(m) and (
                        is_ignored(m.group(1), ctx.custom_ignores)
                        or is_ignored(m.group(2), ctx.custom_ignores)
                    )
                    if suppress_file:
                        continue
                    in_diff = True
                    emitted_in_commit += 1
                    emitter.line(line)
                    continue

                if suppress_file:
                    continue

                if in_diff and emitted_in_commit >= diff_budget:
                    if not truncation_noted:
                        emitter.line("\n... [DIFF TRUNCATED TO 1000 LINES] ...\n")
                        truncation_noted = True
                    continue

                emitter.line(line)
                if in_diff:
                    emitted_in_commit += 1
    finally:
        try:
            proc.stdout.close()
        except Exception:
            pass
        proc.terminate()
        proc.wait()

    emitter.close_tag("recent_activity")


@register_section("filtered_files", 0.4)
def emit_filtered_files(
    emitter: XmlEmitter, nodes: list[FileNode], ctx: RepoContext
) -> None:
    if not ctx.filtered_files:
        return

    emitter.open_tag("filtered_files")
    emitter.note(
        "Files auto-excluded by binary extension, generated content, ignored-dir membership, "
        "custom ignores, or sensitive naming."
    )

    items = sorted(ctx.filtered_files.items())[:500]
    for path, reason in items:
        emitter.empty_element("  ", "file", {"path": path, "reason": reason})

    if len(ctx.filtered_files) > 500:
        emitter.comment(
            f"{len(ctx.filtered_files) - 500} more filtered files omitted", "  "
        )

    emitter.close_tag("filtered_files")


@register_section("metadata", 0.95)
def emit_metadata(emitter: XmlEmitter, nodes: list[FileNode], ctx: RepoContext) -> None:
    emitter.open_tag("metadata")
    emitter.note(
        "Self-describing section: what was included, what was omitted, and why."
    )

    emitter.open_tag("detection_config", indent="  ")
    for name, value in (
        ("noise_threshold", ctx.noise_threshold),
        ("max_file_lines", ctx.max_file_lines),
        ("skeleton_lines", ctx.skeleton_lines),
        ("diff_per_file", ctx.diff_per_file),
        ("redact_secrets", ctx.redact_secrets),
    ):
        emitter.empty_element("    ", "param", {"name": name, "value": value})
    emitter.close_tag("detection_config", "  ")

    emitter.open_tag("file_emission", indent="  ")
    for name, count in (
        ("full", len(ctx.files_full)),
        ("skeleton", len(ctx.files_skeleton)),
        ("stub", len(ctx.files_stub)),
    ):
        emitter.empty_element("    ", "stat", {"name": name, "count": count})
    emitter.close_tag("file_emission", "  ")

    if ctx.noise_stubs:
        emitter.open_tag("noise_stubs", {"count": len(ctx.noise_stubs)}, "  ")
        for path, reason in sorted(ctx.noise_stubs.items()):
            emitter.empty_element("    ", "file", {"path": path, "reason": reason})
        emitter.close_tag("noise_stubs", "  ")

    if ctx.capped_diff_files:
        emitter.open_tag("capped_diffs", {"count": len(ctx.capped_diff_files)}, "  ")
        for entry in ctx.capped_diff_files:
            emitter.empty_element("    ", "file", {"ref": entry})
        emitter.close_tag("capped_diffs", "  ")

    if ctx.section_errors:
        emitter.open_tag("section_errors", {"count": len(ctx.section_errors)}, "  ")
        for entry in ctx.section_errors:
            emitter.empty_element("    ", "error", {"message": entry})
        emitter.close_tag("section_errors", "  ")

    emitter.close_tag("metadata")


def positive_int(value: str) -> int:
    iv = int(value)
    if iv <= 0:
        raise argparse.ArgumentTypeError(f"expected a positive integer, got '{value}'")
    return iv


def fraction_float(value: str) -> float:
    fv = float(value)
    if not 0.0 <= fv <= 1.0:
        raise argparse.ArgumentTypeError(
            f"expected a value between 0.0 and 1.0, got '{value}'"
        )
    return fv


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export a git repository as structured XML context for AI assistants.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "repo_dir",
        nargs="?",
        default=".",
        help="Path to the git repository (default: current directory)",
    )
    parser.add_argument("--from-commit", default="", help="Start of commit range")
    parser.add_argument(
        "--to-commit", default="", help="End of commit range (default: HEAD)"
    )
    parser.add_argument(
        "-o",
        "--output",
        default="git2ai_context.xml",
        help="Output file path (resolved against your current directory, not the repo)",
    )
    parser.add_argument(
        "--ignore",
        action="append",
        default=[],
        dest="custom_ignores",
        metavar="PATTERN",
        help="Glob pattern or directory prefix to ignore (repeatable)",
    )
    parser.add_argument(
        "--max-file-lines",
        type=positive_int,
        default=1500,
        help="Files larger than this are skeleton-extracted (default: 1500)",
    )
    parser.add_argument(
        "--skeleton-lines",
        type=positive_int,
        default=100,
        help="Lines to keep when skeletonizing (default: 100)",
    )
    parser.add_argument(
        "--diff-per-file",
        type=positive_int,
        default=200,
        help="Max diff lines per file in uncommitted_changes (default: 200)",
    )
    parser.add_argument(
        "--noise-threshold",
        type=fraction_float,
        default=0.5,
        help="Files scoring above this are stubbed (default: 0.5). Set to 1.0 to disable.",
    )
    parser.add_argument(
        "--no-redact-secrets",
        action="store_true",
        default=False,
        help="Disable redaction of API keys, tokens, and other secrets.",
    )

    return parser.parse_args()


def run_sections(emitter: XmlEmitter, nodes: list[FileNode], ctx: RepoContext) -> None:
    sections_by_priority = sorted(
        (s for s in SECTION_REGISTRY if s.name != "metadata"),
        key=lambda s: -s.priority,
    )
    metadata_spec = next((s for s in SECTION_REGISTRY if s.name == "metadata"), None)

    for spec in sections_by_priority:
        try:
            spec.emitter(emitter, nodes, ctx)
        except Exception as exc:
            warn(f"section {spec.name} failed: {exc}")
            ctx.section_errors.append(f"{spec.name}: {exc}")
            emitter.comment(f"ERROR in {spec.name}: {exc}")

    if metadata_spec:
        try:
            metadata_spec.emitter(emitter, nodes, ctx)
        except Exception as exc:
            warn(f"metadata section failed: {exc}")
            ctx.section_errors.append(f"metadata: {exc}")


def main() -> None:
    args = parse_args()

    if not shutil.which("git"):
        sys.exit("Error: git CLI is required to run this script.")

    env = git_env()
    repo_root = resolve_repo_root(args.repo_dir, env)
    output_path = os.path.abspath(args.output)
    os.chdir(repo_root)

    excluded_paths: set[str] = set()
    rel_output = os.path.relpath(output_path, repo_root)
    if not rel_output.startswith(".."):
        excluded_paths.add(rel_output.replace(os.sep, "/"))

    range_args = build_range_args(args.from_commit, args.to_commit)
    target_head = resolve_target_head(range_args, env)

    ctx = RepoContext(
        repo_root=repo_root,
        env=env,
        target_head=target_head,
        range_args=range_args,
        custom_ignores=args.custom_ignores,
        redact_secrets=not args.no_redact_secrets,
        max_file_lines=args.max_file_lines,
        skeleton_lines=args.skeleton_lines,
        diff_per_file=args.diff_per_file,
        noise_threshold=args.noise_threshold,
        excluded_paths=excluded_paths,
    )

    sys.stderr.write("Computing churn metrics...\n")
    file_churn, cochange_pairs = compute_churn_metrics(
        range_args, args.custom_ignores, env
    )
    ctx.churn_hotspots = {f for f, _ in file_churn.most_common(15)}
    ctx.cochange_pairs = cochange_pairs

    sys.stderr.write("Enumerating files...\n")
    nodes = enumerate_nodes(ctx)
    ctx.diffs = git_diff_all(env)
    ctx.test_pairs = detect_test_pairs({n.path for n in nodes})

    sys.stderr.write("Analyzing file contents...\n")
    analyze_nodes(nodes, ctx)
    finalize_graph(nodes, ctx)

    for node in nodes:
        node.priority_score = compute_priority_score(node, ctx)

    with open(output_path, "w", encoding="utf-8", errors="replace") as out:
        emitter = XmlEmitter(out, ctx)
        emitter.write('<?xml version="1.0" encoding="UTF-8"?>\n<git2ai_export>\n')
        try:
            run_sections(emitter, nodes, ctx)
        finally:
            emitter.write("</git2ai_export>\n")

    size_mb = os.path.getsize(output_path) / (1024 * 1024)
    sys.stderr.write(f"\nContext Output: {output_path} ({size_mb:.1f} MB)\n")
    sys.stderr.write(
        f"Files: {len(ctx.files_full)} full, {len(ctx.files_skeleton)} skeleton, "
        f"{len(ctx.files_stub)} stub\n"
    )

    if ctx.section_errors:
        sys.exit(1)


if __name__ == "__main__":
    main()
