return {
  {
    "folke/snacks.nvim",
    priority = 1000,
    lazy = false,
    ---@type snacks.Config
    opts = {
      bigfile = { enabled = true },
      input = { enabled = true },
      notifier = { enabled = true, timeout = 3000 },
      picker = { enabled = true },
      quickfile = { enabled = true },
      scope = { enabled = true },
      words = { enabled = true },
      explorer = { enabled = false }, -- oil owns files
    },
    keys = {
      -- hidden+ignored so .env shows; java build junk stays excluded
      { "<leader><space>", function() Snacks.picker.smart({ hidden = true, ignored = true, exclude = { "target", "build", "out", ".gradle", "*.class", "*.log" } }) end, desc = "Smart find files" },
      { "<leader>,", function() Snacks.picker.buffers() end, desc = "Buffers" },
      { "<leader>/", function() Snacks.picker.grep() end, desc = "Grep" },
      { "<leader>:", function() Snacks.picker.command_history() end, desc = "Command history" },
      { "<leader>ff", function() Snacks.picker.files({ hidden = true, ignored = true, exclude = { "target", "build", "out", ".gradle", "*.class", "*.log" } }) end, desc = "Find files" },
      { "<leader>fg", function() Snacks.picker.git_files() end, desc = "Find git files" },
      { "<leader>fr", function() Snacks.picker.recent() end, desc = "Recent" },
      { "<leader>fc", function() Snacks.picker.files({ cwd = vim.fn.stdpath("config") }) end, desc = "Find config file" },
      { "<leader>fp", function() Snacks.picker.projects() end, desc = "Projects" },
      { "<leader>sb", function() Snacks.picker.lines() end, desc = "Buffer lines" },
      { "<leader>sd", function() Snacks.picker.diagnostics() end, desc = "Diagnostics" },
      { "<leader>sD", function() Snacks.picker.diagnostics_buffer() end, desc = "Buffer diagnostics" },
      { "<leader>sh", function() Snacks.picker.help() end, desc = "Help pages" },
      { "<leader>sk", function() Snacks.picker.keymaps() end, desc = "Keymaps" },
      { "<leader>sR", function() Snacks.picker.resume() end, desc = "Resume picker" },
      { "<leader>gb", function() Snacks.picker.git_branches() end, desc = "Git branches" },
      { "<leader>gl", function() Snacks.picker.git_log() end, desc = "Git log" },
      { "<leader>gs", function() Snacks.picker.git_status() end, desc = "Git status" },
      { "<leader>gd", function() Snacks.picker.git_diff() end, desc = "Git diff hunks" },
      { "<leader>gB", function() Snacks.gitbrowse() end, desc = "Git browse", mode = { "n", "v" } },
      { "<leader>gg", function() Snacks.lazygit() end, desc = "Lazygit" },
      { "<C-/>", function() Snacks.terminal() end, desc = "Toggle terminal" },
      { "<C-_>", function() Snacks.terminal() end, desc = "which_key_ignore" },
      { "<leader>bd", function() Snacks.bufdelete() end, desc = "Delete buffer" },
      { "<leader>Z", function() Snacks.zen.zoom() end, desc = "Toggle zen zoom" },
      { "<leader>cR", function() Snacks.rename.rename_file() end, desc = "Rename file" },
      { "]]", function() Snacks.words.jump(vim.v.count1) end, desc = "Next reference", mode = { "n", "t" } },
      { "[[", function() Snacks.words.jump(-vim.v.count1) end, desc = "Prev reference", mode = { "n", "t" } },
    },
  },
}
